spring:
  jpa:
    hibernate:
#      ddl-auto: update
      naming:
        physical-strategy=org:
          hibernate:
            boot:
              model:
                naming:
                  PhysicalNamingStrategyStandardImpl:show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/interview_guide
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
